version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - aws iam attach-role-policy --role-name codebuild-revature-expense-tracker-build-service-role --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
      - echo Installing dependencies...
      - cd backend
      - npm install
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - cd backend
      - echo Running tests...
      - npm run test
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging the files...
      - mkdir app
      - cp -r backend/* ./app
      - zip -r app.zip ./app
artifacts:
  files:
    - app.zip
  discard-paths: yes
