version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging the files...
      - cd backend
      - mkdir app
      - cp -r ./* ./app
      - zip -r ../app.zip ./app
      - cd ..
artifacts:
  files:
    - app.zip
  discard-paths: yes
